### ISSUE TITLE
request 

### ISSUE THREAD

**Issue by Santhoshstark06** [cyrixninja/RetroDino#1]
Hey harsh kumar , i'm a beginner in github so can you say how did you merge the files in github and giving the output?
and also suggest some yt channels for to do that .

**Comment by cyrixninja** [comment]
Just text me on discord at cyrixninja#0157 and I'll guide you

**Comment by Santhoshstark06** [comment]
Hey harsh, you didn't send your discord ID correctly can you check it and
send again.

**Comment by cyrixninja** [comment]
cyrixninja#0157

**Comment by cyrixninja** [comment]
cyrixninja# 0157
